services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  servico-b:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servico-b
    environment:
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8081:8081"
    depends_on:
      - zipkin
    entrypoint: ["/root/servico-b"]

  servico-a:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servico-a
    environment:
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - servico-b
      - zipkin
    entrypoint: ["/root/servico-a"]
